### ISSUE TITLE
(JP)多段GpuNestLoopをプランナに選ばせることが出来ない

### ISSUE THREAD

**Issue by onlyindreams** [heterodb/pg-strom#202]
バグかどうかは判断がつきませんが、現在のマスタ(cf3e87af9dea018f99195361c664b85bfb0129b7)では、enable_gpuhashjoinをoffにしても多段GpuNestLoopを選ぶことができないようです。

再現クエリ

```
drop table if exists t1;
drop table if exists t2;
drop table if exists t3;
create table t1(id integer);
create table t2(id integer);
create table t3(id integer);
insert into t1 select generate_series(1,100);
insert into t2 select generate_series(1,10);
insert into t3 select generate_series(1,10);
set client_min_messages=debug1;
set log_min_messages=debug1;
set pg_strom.enable_gpuhashjoin to off;
set pg_strom.gpu_setup_cost=0;
explain select * from t1 natural join t2 natural join t3;


nanzai=# explain select * from t1 natural join t2 natural join t3;
DEBUG:  GpuJoin: t1 INL t2 IHJ t3 Cost=113.17..4258.45
DEBUG:  GpuJoin: t1 INL t3 IHJ t2 Cost=113.17..4258.45
DEBUG:  GpuJoin: t2 INL t3 IHJ t1 Cost=113.17..4258.45
                                  QUERY PLAN                                  
------------------------------------------------------------------------------
 Custom Scan (GpuJoin)  (cost=113.17..4258.45 rows=414528 width=4)
   Bulkload: On (density: 100.00%)
   Depth 1: GpuNestLoop, JoinQual: (id = id)
            Nrows (in/out: 100.00%), KDS-Heap (size: 137.02KB, nbatches: 1)
   Depth 2: GpuHashJoin, HashKeys: (id), JoinQual: (id = id)
            Nrows (in/out: 16256.00%), KDS-Hash (size: 165.02KB, nbatches: 1)
   ->  Custom Scan (BulkScan) on t1  (cost=0.00..35.50 rows=2550 width=4)
   ->  Seq Scan on t2  (cost=0.00..35.50 rows=2550 width=4)
   ->  Seq Scan on t3  (cost=0.00..35.50 rows=2550 width=4)
(9 rows)
```

enable_gpuhashjoinがoffでも、hash_clauseがNILでない場合はgpu_hashjoinのコストを計算するようにしているため、GpuHashJoinが選ばれてしまうように見えています。

バックトレース

```
(gdb) bt
#0  cost_gpujoin (root=0x23a9778, joinrel=0x23c1fd8, gpath=0x23c3a50, required_outer=0x0, 
    support_bulkload=1 '\001') at src/gpujoin.c:759
#1  0x00007f07aaaa671a in create_gpujoin_path (root=0x23a9778, joinrel=0x23c1fd8, outer_path=0x23ab9e8, 
    inner_path_list=0x23c4910, param_info=0x0, required_outer=0x0, support_bulkload=1 '\001')
    at src/gpujoin.c:943
#2  0x00007f07aaaa7258 in gpujoin_add_join_path (root=0x23a9778, joinrel=0x23c1fd8, outerrel=0x23aa658,  ★ここはGpuNestLoopのロジックパスのようですが、内部のcost_gpujoinではhash_clauseのみを見ているため、GpuHashJoinのコストを計算してしまっています。
    innerrel=0x23aa980, jointype=JOIN_INNER, extra=0x7fff09745880) at src/gpujoin.c:1292
#3  0x0000000000703034 in add_paths_to_joinrel (root=0x23a9778, joinrel=0x23c1fd8, outerrel=0x23ae180, 
    innerrel=0x23aa330, jointype=JOIN_INNER, sjinfo=0x7fff09745920, restrictlist=0x23c4468)
    at joinpath.c:269
#4  0x0000000000705534 in make_join_rel (root=0x23a9778, rel1=0x23ae180, rel2=0x23aa330)
    at joinrels.c:689
#5  0x0000000000704c43 in make_rels_by_clause_joins (root=0x23a9778, old_rel=0x23ae180, 
    other_rels=0x23abc18) at joinrels.c:274
#6  0x00000000007048e9 in join_search_one_level (root=0x23a9778, level=3) at joinrels.c:96
#7  0x00000000006f12e9 in standard_join_search (root=0x23a9778, levels_needed=3, initial_rels=0x23abc40)
    at allpaths.c:1810
#8  0x00000000006f1265 in make_rel_from_joinlist (root=0x23a9778, joinlist=0x23aacd0) at allpaths.c:1741
#9  0x00000000006eefce in make_one_rel (root=0x23a9778, joinlist=0x23aacd0) at allpaths.c:169
#10 0x0000000000716573 in query_planner (root=0x23a9778, tlist=0x23a9bd0, 
    qp_callback=0x71befa <standard_qp_callback>, qp_extra=0x7fff09745cd0) at planmain.c:236
#11 0x0000000000718dad in grouping_planner (root=0x23a9778, tuple_fraction=0) at planner.c:1535
#12 0x000000000071742d in subquery_planner (glob=0x23a96e0, parse=0x2367e78, parent_root=0x0, 
    hasRecursion=0 '\000', tuple_fraction=0, subroot=0x7fff09746068) at planner.c:612
#13 0x0000000000716824 in standard_planner (parse=0x2367e78, cursorOptions=0, boundParams=0x0)
    at planner.c:229
#14 0x00007f07aaa89b98 in pgstrom_planner_entrypoint (parse=0x2367e78, cursorOptions=0, boundParams=0x0)
    at src/main.c:341
#15 0x0000000000716665 in planner (parse=0x2367e78, cursorOptions=0, boundParams=0x0) at planner.c:155
#16 0x00000000007d4433 in pg_plan_query (querytree=0x2367e78, cursorOptions=0, boundParams=0x0)
    at postgres.c:809
#17 0x00000000005f48de in ExplainOneQuery (query=0x2367e78, into=0x0, es=0x2367da8, 
    queryString=0x2358808 "explain select * from t1 natural join t2 natural join t3;", params=0x0)
    at explain.c:351
#18 0x00000000005f4604 in ExplainQuery (stmt=0x2359760, 
    queryString=0x2358808 "explain select * from t1 natural join t2 natural join t3;", params=0x0, 
    dest=0x2367d10) at explain.c:245
#19 0x00000000007dc6bc in standard_ProcessUtility (parsetree=0x2359760, 
    queryString=0x2358808 "explain select * from t1 natural join t2 natural join t3;", 
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x2367d10, completionTag=0x7fff09746480 "")
    at utility.c:658
#20 0x00000000007dbeda in ProcessUtility (parsetree=0x2359760, 
    queryString=0x2358808 "explain select * from t1 natural join t2 natural join t3;", 
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0x2367d10, completionTag=0x7fff09746480 "")
    at utility.c:334
#21 0x00000000007daf69 in PortalRunUtility (portal=0x22fcfe8, utilityStmt=0x2359760, 
    isTopLevel=1 '\001', dest=0x2367d10, completionTag=0x7fff09746480 "") at pquery.c:1187
#22 0x00000000007dacce in FillPortalStore (portal=0x22fcfe8, isTopLevel=1 '\001') at pquery.c:1061
#23 0x00000000007da5f5 in PortalRun (portal=0x22fcfe8, count=9223372036854775807, isTopLevel=1 '\001', 
---Type <return> to continue, or q <return> to quit---
    dest=0x239c7f0, altdest=0x239c7f0, completionTag=0x7fff09746670 "") at pquery.c:785
#24 0x00000000007d48e7 in exec_simple_query (
    query_string=0x2358808 "explain select * from t1 natural join t2 natural join t3;")
    at postgres.c:1104
#25 0x00000000007d8915 in PostgresMain (argc=1, argv=0x22e3d78, dbname=0x22e3be0 "nanzai", 
    username=0x22e3bc0 "nanzai") at postgres.c:4025
#26 0x000000000075b556 in BackendRun (port=0x230be30) at postmaster.c:4230
#27 0x000000000075acc9 in BackendStartup (port=0x230be30) at postmaster.c:3906
#28 0x00000000007574a2 in ServerLoop () at postmaster.c:1665
#29 0x0000000000756ae9 in PostmasterMain (argc=1, argv=0x22e2b80) at postmaster.c:1274
#30 0x00000000006b0f32 in main (argc=1, argv=0x22e2b80) at main.c:223
```

**Comment by onlyindreams** [comment]
ちなみにhash_clauseがNULLになる条件でも多段GpuNestLoopにはなりませんでした。

```

nanzai=# explain select * from t1, t2,t3 where t1.id>t2.id and t2.id>t3.id
;
2015-09-28 18:48:39 JST nanzai nanzai 20405 DEBUG:  00000: GpuJoin: t1 INL t2 Cost=81.93..931.93
2015-09-28 18:48:39 JST nanzai nanzai 20405 LOCATION:  cost_gpujoin, gpujoin.c:869
DEBUG:  GpuJoin: t1 INL t2 Cost=81.93..931.93
2015-09-28 18:48:39 JST nanzai nanzai 20405 DEBUG:  00000: GpuJoin: t2 INL t1 Cost=33.02..883.02
2015-09-28 18:48:39 JST nanzai nanzai 20405 LOCATION:  cost_gpujoin, gpujoin.c:869
DEBUG:  GpuJoin: t2 INL t1 Cost=33.02..883.02
2015-09-28 18:48:39 JST nanzai nanzai 20405 DEBUG:  00000: GpuJoin: t2 INL t3 Cost=579.11..22254.11
2015-09-28 18:48:39 JST nanzai nanzai 20405 LOCATION:  cost_gpujoin, gpujoin.c:869
DEBUG:  GpuJoin: t2 INL t3 Cost=579.11..22254.11
2015-09-28 18:48:39 JST nanzai nanzai 20405 DEBUG:  00000: GpuJoin: t3 INL t2 Cost=579.11..22254.11
2015-09-28 18:48:39 JST nanzai nanzai 20405 LOCATION:  cost_gpujoin, gpujoin.c:869
DEBUG:  GpuJoin: t3 INL t2 Cost=579.11..22254.11
2015-09-28 18:48:39 JST nanzai nanzai 20405 DEBUG:  00000: GpuJoin: (t1, t2) INL t3 Cost=17236.03..739736.04
2015-09-28 18:48:39 JST nanzai nanzai 20405 LOCATION:  cost_gpujoin, gpujoin.c:869
DEBUG:  GpuJoin: (t1, t2) INL t3 Cost=17236.03..739736.04
2015-09-28 18:48:39 JST nanzai nanzai 20405 DEBUG:  00000: GpuJoin: t2 INL t1 INL t3 Cost=19650.66..742150.66
2015-09-28 18:48:39 JST nanzai nanzai 20405 LOCATION:  cost_gpujoin, gpujoin.c:869
DEBUG:  GpuJoin: t2 INL t1 INL t3 Cost=19650.66..742150.66
2015-09-28 18:48:39 JST nanzai nanzai 20405 DEBUG:  00000: GpuJoin: t3 INL (t1, t2) Cost=18675.72..741175.72
2015-09-28 18:48:39 JST nanzai nanzai 20405 LOCATION:  cost_gpujoin, gpujoin.c:869
DEBUG:  GpuJoin: t3 INL (t1, t2) Cost=18675.72..741175.72
2015-09-28 18:48:39 JST nanzai nanzai 20405 DEBUG:  00000: GpuJoin: (t2, t3) INL t1 Cost=4477.47..738663.57
2015-09-28 18:48:39 JST nanzai nanzai 20405 LOCATION:  cost_gpujoin, gpujoin.c:869
DEBUG:  GpuJoin: (t2, t3) INL t1 Cost=4477.47..738663.57
                                     QUERY PLAN                                     
------------------------------------------------------------------------------------
 Custom Scan (GpuJoin)  (cost=4477.47..738663.57 rows=72250000 width=12)
   Bulkload: Off
   Depth 1: GpuNestLoop, JoinQual: (id > id)
            Nrows (in/out: 3333.33%), KDS-Heap (size: 11.31KB, nbatches: 1)
   ->  Custom Scan (GpuJoin)  (cost=579.11..22254.11 rows=2167500 width=8)
         Bulkload: On (density: 100.00%)
         Depth 1: GpuNestLoop, JoinQual: (id > id)
                  Nrows (in/out: 85000.00%), KDS-Heap (size: 137.02KB, nbatches: 1)
         ->  Custom Scan (BulkScan) on t2  (cost=0.00..35.50 rows=2550 width=4)
         ->  Seq Scan on t3  (cost=0.00..35.50 rows=2550 width=4)
   ->  Seq Scan on t1  (cost=0.00..2.00 rows=100 width=4)
(11 rows)
```
