### ISSUE TITLE
 WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered ERROR:  (gpupreagg.c:5197) failed on cuEventSynchronize: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered

### ISSUE THREAD

**Issue by TheFrancisHe** [heterodb/pg-strom#374]
When i run a TPC-H test , pg_strom returns warnings & errors  like this ,

```
GpuPreAgg: expand final hash slot 3102960 -> 6205920 (0 dropped)
GpuPreAgg: expand final hash slot 6205920 -> 12411840 (0 dropped)
GpuPreAgg: expand final hash slot 12411840 -> 24823680 (0 dropped)
GpuPreAgg: expand final hash slot 24823680 -> 49647360 (0 dropped)
GpuPreAgg: expand final hash slot 49647360 -> 99294720 (0 dropped)
GpuPreAgg: expand final hash slot 99294720 -> 178508211 (0 dropped)
Error: (gpupreagg.c:5197) failed on cuEventSynchronize: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
ERROR:  (gpupreagg.c:5197) failed on cuEventSynchronize: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
STATEMENT:  select
                c_name,
                c_custkey,
                o_orderkey,
                o_orderdate,
                o_totalprice,
                sum(l_quantity)
        from
                customer,
                orders,
                lineitem
        where
                o_orderkey in (
                        select
                                l_orderkey
                        from
                                lineitem
                        group by
                                l_orderkey having
                                        sum(l_quantity) > 312
                )
                and c_custkey = o_custkey
                and o_orderkey = l_orderkey
        group by
                c_name,
                c_custkey,
                o_orderkey,
                o_orderdate,
                o_totalprice
        order by
                o_totalprice desc,
                o_orderdate
        LIMIT 100;
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
WARNING:  failed on cuEventRecord: CUDA_ERROR_ILLEGAL_ADDRESS - an illegal memory access was encountered
```
FYI,  the total amount of the test db is about 172GB ,including indexes && sequence .
```
tpch=# \d+
                                List of relations
 Schema |          Name          |   Type   |  Owner   |    Size    | Description 
--------+------------------------+----------+----------+------------+-------------
 public | customer               | table    | postgres | 2317 MB    | 
 public | customer_c_custkey_seq | sequence | postgres | 8192 bytes | 
 public | lineitem               | table    | postgres | 74 GB      | 
 public | nation                 | table    | postgres | 40 kB      | 
 public | nation_n_nationkey_seq | sequence | postgres | 8192 bytes | 
 public | orders                 | table    | postgres | 17 GB      | 
 public | orders_o_orderkey_seq  | sequence | postgres | 8192 bytes | 
 public | part                   | table    | postgres | 2562 MB    | 
 public | part_p_partkey_seq     | sequence | postgres | 8192 bytes | 
 public | partsupp               | table    | postgres | 11 GB      | 
 public | region                 | table    | postgres | 40 kB      | 
 public | region_r_regionkey_seq | sequence | postgres | 8192 bytes | 
 public | supplier               | table    | postgres | 144 MB     | 
 public | supplier_s_suppkey_seq | sequence | postgres | 8192 bytes | 
(14 rows)
```
Environment:
OS: CentOS Linux release 7.5.1804 (Core) 
Postgres 9.6.2, PG-strom master branch version (June 18, 2018)
filesystem  xfs
CUDA 9.2
```
[root@postgres ~]# nvidia-smi 
Thu Jun 28 17:03:35 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           Off  | 00000000:04:00.0 Off |                    0 |
| N/A   43C    P0    50W / 250W |    169MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     12036      C   ...bgworker: PG-Strom GPU memory keeper      159MiB |
+-----------------------------------------------------------------------------+
```
is this a bug of pg_strom or not ？

plz help to check .

best regards,
Francis

**Comment by kaigai** [comment]
http://heterodb.github.io/pg-strom/tutorial/#collecting-crash-dump
Could you provide us crash dump of the GPU kernel when it reports the error?
Please don't forget to set `pg_strom.debug_jit_compile_options = on` to keep symbol information.

**Comment by kaigai** [comment]
BTW, collection of GPU crash dump usually takes long time (15-30min).

**Comment by TheFrancisHe** [comment]
FYI: 
here are some system log info below ：
```
[14047.198650] perf: interrupt took too long (2512 > 2500), lowering kernel.perf_event_max_sample_rate to 79000
[15392.986114] nvidia 0000:04:00.0: irq 93 for MSI/MSI-X
[15399.110810] nvidia 0000:04:00.0: irq 93 for MSI/MSI-X
[15424.123020] nvidia 0000:04:00.0: irq 93 for MSI/MSI-X
[15430.186423] nvidia 0000:04:00.0: irq 93 for MSI/MSI-X
[15494.461626] perf: interrupt took too long (3150 > 3140), lowering kernel.perf_event_max_sample_rate to 63000
[17157.817924] nvidia 0000:04:00.0: irq 93 for MSI/MSI-X
[17163.818207] nvidia 0000:04:00.0: irq 93 for MSI/MSI-X
[18633.119891] nvidia 0000:04:00.0: irq 93 for MSI/MSI-X
[18639.129866] nvidia 0000:04:00.0: irq 93 for MSI/MSI-X
[18796.292110] nvidia 0000:04:00.0: irq 93 for MSI/MSI-X
[18802.360449] nvidia 0000:04:00.0: irq 93 for MSI/MSI-X
[19106.215961] perf: interrupt took too long (3943 > 3937), lowering kernel.perf_event_max_sample_rate to 50000
```

**Comment by kaigai** [comment]
Thanks for your cooperation.

Could you show us the backtrace which shows the function name and line number when GPU kernel got crashed?
If it is not obvious why it caused `CUDA_ERROR_ILLEGAL_ADDRESS`, I may ask you to upload the dump image to our FTP server.

**Comment by TheFrancisHe** [comment]
hi kaigai, 

Thanks again ,

i'll give it a shot  .:smile:

It may need some time.

best regards
Francis

**Comment by mgoyder** [comment]
Was this resolved or understood? I am seeing the same issues also on TPC-H queries.

**Comment by kaigai** [comment]
Could you show us where the GPU kernel made segmentation fault?

http://heterodb.github.io/pg-strom/troubles/#collecting-crash-dump

**Comment by TheFrancisHe** [comment]
> Was this resolved or understood? I am seeing the same issues also on TPC-H queries.

There is  a workaround to this issue : 
Don't add the option **--enable-debug** during the installation procedure _./configure_ .  

For some reasons , i have not found the root cause yet .

I hope this will help you.

**Comment by mgoyder** [comment]
> Could you show us where the GPU kernel made segmentation fault?
> 
> http://heterodb.github.io/pg-strom/troubles/#collecting-crash-dump

I have a .nvcudmp -- do you have a FTP area into which I can upload it?

**Comment by mgoyder** [comment]
> Could you show us where the GPU kernel made segmentation fault?
> 
> http://heterodb.github.io/pg-strom/troubles/#collecting-crash-dump

Also, I tried to get a dump with debug_jit_compile_options = on, but with this setting the issue does not repro. 😩

**Comment by kaigai** [comment]
> I have a .nvcudmp -- do you have a FTP area into which I can upload it?

Can you cut&paste its backtrace once?
Probably, dump file without `debug_jit_compile_options` will less make sense...

This configuration enables:
- `--device-debug` nvrtc option
- `--generate-line-info` nvrtc option

and, current code does not change code path or structure definitions. I'm wondering.

**Comment by mgoyder** [comment]
> Can you cut&paste its backtrace once?

```
(cuda-gdb) target cudacore /db/pg11.2-xeon-e3/core_1552001843_KBL-Xeon-E3_RTX-2080_7454.nvcudmp
Opening GPU coredump: /db/pg11.2-xeon-e3/core_1552001843_KBL-Xeon-E3_RTX-2080_7454.nvcudmp
[New Thread 7456]

Assertion failed.
[Current focus set to CUDA kernel 0, grid 1, block (39,0,0), thread (37,0,0), device 0, sm 33, warp 1, lane 5]
#0  0x00007f21441b4340 in gpujoin_main<<<(46,1,1),(256,1,1)>>> ()
(cuda-gdb) bt
#0  0x00007f21441b4340 in gpujoin_main<<<(46,1,1),(256,1,1)>>> ()
```

As I mentioned, enabling `debug_jit_compile_options` resulted in no repro.

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
