### ISSUE TITLE
CUDA10.2 nvrtcCompileProgram() likely goes to infinite loops

### ISSUE THREAD

**Issue by kaigai** [heterodb/pg-strom#451]
# Problems

On some device code, `nvrtcCompileProgram()` of CUDA 10.2 likely goes to infinite loops.
Once code builder worker falled into the problem, CPU consumption becomes 100% in the `/usr/local/cuda-10.2/lib64/libnvrtc.so.10.2`, and control will not be backed to the caller.
This problem will happen on a limited number of device code, not all the cases. However, it always causes the problem on the "problematic" device code.

Below is output of `top` command. `nvrtcc` is our test program for this problem.
```
top - 03:23:01 up  3:18,  4 users,  load average: 0.24, 0.20, 0.22
Tasks: 306 total,   2 running, 304 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.2 us,  0.0 sy,  0.0 ni, 95.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 19668712+total, 18429830+free,  2053408 used, 10335404 buff/cache
KiB Swap: 12582908 total, 12582908 free,        0 used. 19326177+avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 85963 kaigai    20   0   66488  32672  14916 R 100.0  0.0   0:15.40 nvrtcc
 85956 kaigai    20   0   58560   2440   1520 R   0.7  0.0   0:01.15 top
     1 root      20   0  193928   7020   4176 S   0.0  0.0   0:04.02 systemd
     2 root      20   0       0      0      0 S   0.0  0.0   0:00.01 kthreadd
     3 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/0+
     4 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0+
```

And, `bt` (backtrace) command of `gdb` says it is in the `/usr/local/cuda-10.2/lib64/libnvrtc.so.10.2`.
```
$ gdb -p 85963
    :
(gdb) bt
#0  0x00007fe5dc39f079 in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#1  0x00007fe5dc343494 in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#2  0x00007fe5dc33f7fb in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#3  0x00007fe5dca24359 in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#4  0x00007fe5dca2a5e6 in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#5  0x00007fe5dc322df8 in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#6  0x00007fe5dc322feb in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#7  0x00007fe5dc32227f in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#8  0x00007fe5dc3d5cd1 in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#9  0x00007fe5dc3d79ba in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#10 0x00007fe5dc3c1fe7 in ?? ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#11 0x00007fe5dc2885f6 in nvrtcCompileProgram ()
   from /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2
#12 0x0000000000400e9d in main (argc=<optimized out>, argv=<optimized out>)
    at nvrtcc.c:114
```

# Steps to reproduce

For RHEL7/CentOS7
```
$ sudo yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
$ sudo yum install postgresql11-server postgresql11-devel
$ git clone https://github.com/heterodb/pg-strom.git
$ git clone https://github.com/heterodb/toybox.git
$ cd toybox/nvrtc
$ make PG_CONFIG=/usr/pgsql-11/bin/pg_config CUDA_PATH=/usr/local/cuda-10.2
$ env LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64 \
   ./nvrtcc -I ../../pg-strom/src pgsql_tmp_strom_50518.1.gpu
^C
```

The device code `pgsql_tmp_strom_50518.1.gpu` makes nvrtc busy loop, however, we have no idea which portion makes the problem.

This problem happens **only CUDA 10.2**.
We could not reproduce the problem at CUDA 10.1, as follows:
```
$ make PG_CONFIG=/usr/pgsql-11/bin/pg_config CUDA_PATH=/usr/local/cuda-10.1
$ env LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64 \
   ./nvrtcc -I ../../pg-strom/src pgsql_tmp_strom_50518.1.gpu -o hoge.ptx
$ echo $?
0
```

## Software version
- OS: CentOS 7 (kernel: 3.10.0-1062.9.1.el7.x86_64)
- Glibc: glibc-2.17-292.el7.x86_64
- Gcc: gcc-4.8.5-39.el7.x86_64
- CUDA Toolkit 10.2
    - cuda-10.2.89-1.x86_64
    - nvidia driver: 440.33.01

# Workaround

Please don't upgrade your CUDA environment to 10.2, preserve your CUDA 10.1 environment.

# Status of the problem

This problem is reported to NVIDIA. Now waiting for their response.

**Comment by kaigai** [comment]
21st-Dec, NVIDIA notified:

Bug link: https://partners.nvidia.com/bug/viewbug/2789741

The following items have been modified for this bug:
 - Status changed from "Open - pending review" to "Open - Fix being tested"

**Comment by kaigai** [comment]
22nd-Jan, NVIDIA notified:

Bug link: https://partners.nvidia.com/bug/viewbug/2789741

The following items have been modified for this bug:
 - Status changed from "Open - Fix being tested" to "Closed - Fixed"

**Comment by kaigai** [comment]
CUDA 11 Fixed the issue.
