### ISSUE TITLE
Bug? GPU service dies, segmentation fault

### ISSUE THREAD

**Issue by 0-kaz** [heterodb/pg-strom#609]
コミット
80efab9a0ea7f178bc7c267eda3ae2113e4cc1c7

現象
GROUP BYを含むクエリをGPUで実行すると、データ型によってGPUサービスがSegmentation Faultで落ちる

再現手順

準備：
```sql
SET pg_strom.regression_test_mode = on;
SET client_min_messages = error;
DROP SCHEMA IF EXISTS gpu_cache_temp_test CASCADE;
CREATE SCHEMA gpu_cache_temp_test;
CREATE EXTENSION IF NOT EXISTS pg_strom;
RESET client_min_messages;
SET search_path = gpu_cache_temp_test,public;

CREATE TABLE group_test_1 (
  id   int,
  a    int1,
  b    int2,
  c    int4,
  d    int8,
  e    float2,
  f    float4,
  g    float8,
  h    text,
  i    varchar(32),
  j    char(32)
);

INSERT INTO group_test_1 (
  SELECT x,
pgstrom.random_int(1,1,50),
pgstrom.random_int(1,1,50),
pgstrom.random_int(1,1,50),
pgstrom.random_int(1,1,50),
pgstrom.random_int(1,1,50),
pgstrom.random_int(1,1,50),
pgstrom.random_int(1,1,50),
MD5((x%40)::TEXT),
MD5((x%40)::TEXT),
MD5((x%40)::TEXT)
from generate_series(1,100000) x
);
```

クエリとクライアント側出力メッセージ
```
postgres=# select b,min(a) from group_test_1 group by b;
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
```

発生時のサーバ側ログ
```
2023-05-26 10:57:06.973 JST [231073] LOG:  background worker "PG-Strom GPU Service" (PID 231299) was terminated by signal 11: Segmentation fault
2023-05-26 10:57:06.973 JST [231073] LOG:  terminating any other active server processes
2023-05-26 10:57:06.977 JST [231657] FATAL:  the database system is in recovery mode
2023-05-26 10:57:06.985 JST [231073] LOG:  all server processes terminated; reinitializing
2023-05-26 10:57:08.362 JST [231675] LOG:  database system was interrupted; last known up at 2023-05-26 10:49:20 JST
2023-05-26 10:57:08.373 JST [231675] LOG:  database system was not properly shut down; automatic recovery in progress
2023-05-26 10:57:08.374 JST [231675] LOG:  redo starts at 0/2ACB7F0
2023-05-26 10:57:08.374 JST [231675] LOG:  invalid record length at 0/2ACB828: wanted 24, got 0
2023-05-26 10:57:08.374 JST [231675] LOG:  redo done at 0/2ACB7F0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2023-05-26 10:57:08.375 JST [231676] LOG:  checkpoint starting: end-of-recovery immediate wait
2023-05-26 10:57:08.410 JST [231676] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.036 s, sync=0.001 s, total=0.036 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
2023-05-26 10:57:08.413 JST [231073] LOG:  database system is ready to accept connections
2023-05-26 10:57:09.053 JST [231680] ERROR:  failed on bind('.pg_strom.231073.gpu0.sock'): Address already in use
2023-05-26 10:57:09.297 JST [231073] LOG:  background worker "PG-Strom GPU Service" (PID 231680) exited with exit code 1
```

当該プロセスのコアダンプをバックトレース
```
#0  0x00007f694e3d4a74 in pthread_mutex_lock () from /lib64/libpthread.so.0
#1  0x00007f694bcf8228 in __cufile__open_file () from /lib64/heterodb_extra.so
#2  0x00007f694bcf900b in cufile.read_file_iov_v2 () from /lib64/heterodb_extra.so
#3  0x00007f694d3958ef in gpuDirectFileReadIOV () from /home/onishi/pgbin152/lib/postgresql/pg_strom.so
#4  0x00007f694d3b5f75 in __gpuservLoadKdsCommon () from /home/onishi/pgbin152/lib/postgresql/pg_strom.so
#5  0x00007f694d3b743d in gpuservHandleGpuTaskExec () from /home/onishi/pgbin152/lib/postgresql/pg_strom.so
#6  0x00007f694d3b7f98 in gpuservGpuWorkerMain () from /home/onishi/pgbin152/lib/postgresql/pg_strom.so
#7  0x00007f694e3d21cf in start_thread () from /lib64/libpthread.so.0
#8  0x00007f694d8b0dd3 in clone () from /lib64/libc.so.6
```

発生するデータ型
|データ型|結果|
|---|---|
|int1|OK(発生しない)|
|int2|NG(発生する)|
|int4|NG|
|int8|NG|
|float2|NG|
|float4|NG|
|float8|NG|
|text|NG|
|varchar(32)|NG|
|char(32)|NG|

**Comment by 0-kaz** [comment]
バックトレースの出力は前回と同様でした。ご参考まで
https://github.com/heterodb/pg-strom/issues/589

**Comment by kaigai** [comment]
magroでは再現したのですが、buriでは再現してみませんでした。
ただ、当該環境は heterodb-extra のバージョンが少し古く、ここを最新化してみました。

これで上記の手順を繰り返したところ、クラッシュの再現は見られませんでしたので、
ちょっとご確認いただけますか？
```
[kaigai@magro ~]$ sudo dnf update /dev/shm/heterodb-extra-3.11-1.el8.x86_64.rpm
Updating Subscription Management repositories.
Last metadata expiration check: 0:31:58 ago on Sat 27 May 2023 11:12:25 PM JST.
Dependencies resolved.
==========================================================================================
 Package                 Architecture    Version              Repository             Size
==========================================================================================
Upgrading:
 heterodb-extra          x86_64          3.11-1.el8           @commandline           45 k

Transaction Summary
==========================================================================================
Upgrade  1 Package

Total size: 45 k
Is this ok [y/N]: y
```

**Comment by kaigai** [comment]
すいません、昨晩アップデートしていました。

そして、CUDA 12.1 だと nvcc コンパイラが（！）クラッシュしてしまったのですが、
無事にビルドできましたか？

**Comment by 0-kaz** [comment]
再度確認したところ、Noでした。
アップデート前にコンパイルしていたものが、ちゃんと動作するようになった・・・という状況のようです。

**Comment by kaigai** [comment]
あ、コレはコレで別問題ですので、CUDA 12.0 で動けば本件は close で良いです。

（つか、NVIDIAマターやな…。）

**Comment by 0-kaz** [comment]
わかりました。
12.0で確認して問題なければクローズします

**Comment by 0-kaz** [comment]
12.0でコンパイルOKで、問題も再現しなくなったことを確認しました。
